import {
  imageSection1,
  imageSection2,
  imageSection3,
  imgSlider,
} from "../asset/image/img";
export const links = [
  { id: 1, name: "home" },
  { id: 2, name: "features" },
  { id: 3, name: "testimonial" },
  { id: 4, name: "pricing" },
];
export const section1 = [
  {
    id: 1,
    img: imageSection1.img1,
    title: "vector editing",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
  {
    id: 2,
    img: imageSection1.img2,
    title: "Customize & Monitoring",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
  {
    id: 3,
    img: imageSection1.img3,
    title: "Quality & Short-period",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
];
export const section2 = [
  {
    id: 1,
    img: imageSection2.img1,
    title: "Smart Features",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements. your blood tests.",
  },
  {
    id: 2,
    img: imageSection2.img2,
    title: "Secure Contents",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements. your blood tests.",
  },
];
export const section3 = [
  {
    id: 1,
    img: imageSection3.img1,
    title: "Smart Features",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements",
  },
  {
    id: 2,
    img: imageSection3.img2,
    title: "Fast Performance",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements",
  },
  {
    id: 3,
    img: imageSection3.img3,
    title: "Unlimited Content",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements",
  },
  {
    id: 4,
    img: imageSection3.img4,
    title: "Unlimited Customization",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements",
  },
  {
    id: 5,
    img: imageSection3.img5,
    title: "Boost Productivity",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements",
  },
  {
    id: 6,
    img: imageSection3.img6,
    title: "Customer Support",
    text: "Get your blood tests delivered at let home collect sample from the victory of the managements",
  },
];
export const section5 = [
  {
    id: 1,
    name: "Set disbursement Instructions",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
  {
    id: 2,
    name: "Assembly retrieves funds from your account",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
  {
    id: 3,
    name: "Assembly initiates disbursement",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
  {
    id: 4,
    name: "Customer receives funds payment",
    text: "Get your blood tests delivered at home collect a sample from the your blood tests.",
  },
];
export const dataSlider = [
  {
    id: 1,
    star: 4,
    job: "Modern look & trending design",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person1,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 2,
    star: 5,
    job: "Design Quality & performance",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person2,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 3,
    star: 5,
    job: "Layout and organized layers",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person3,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 4,
    star: 4,
    job: "Modern look & trending design",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person4,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 5,
    star: 4,
    job: "Modern look & trending design",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person4,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 6,
    star: 4,
    job: "Modern look & trending design",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person4,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 7,
    star: 4,
    job: "Modern look & trending design",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person1,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 8,
    star: 5,
    job: "Design Quality & performance",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person2,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 9,
    star: 5,
    job: "Layout and organized layers",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person3,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 10,
    star: 4,
    job: "Modern look & trending design",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person1,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 11,
    star: 5,
    job: "Design Quality & performance",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person2,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
  {
    id: 12,
    star: 5,
    job: "Layout and organized layers",
    text: "Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.",
    avatar: imgSlider.person3,
    name: "Denny Hilguston",
    twitter: "@denny.hil",
  },
];
